version: "3.7"
services: 
    analysis:
        image: data-analysis
        build: .
        volumes: 
            - './hy-data-analysis-with-python-2020/:/usr/hy/'
        ports:
            - 5000:5000